server:
    proxy:
        host: "127.0.0.1"
        port: 8082

    ui:
        host: "127.0.0.1"
        port: 8081

proxy:
    targets:
        - name: api
          path: /api
          url: https://api.example.com

        - name: users
          path: /api/users
          url: https://users.example.com
